apiVersion: v1
kind: Service
metadata:
  name: {{ template "obm.appName" . }}
  {{ include "obm.labels" . | indent 2 }}
  labels:
    app: { template "todo.appName" . }}
    branch: {{ template "obm.branchName" . }}
    {{- range $key, $value := .Values.customLabels }}
    {{ $key }}: {{ $value | quote }}
    {{ - end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "obm.appName" . }}
    branch: {{ template "obm.branchName" . }}
