replicaCount: 1
config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
    tempo:
      endpoint: "tempo:3200"
    loki:
      endpoint: "http://loki:3100/loki/api/v1/push"
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [prometheus]
      traces:
        receivers: [otlp]
        exporters: [tempo]
      logs:
        receivers: [otlp]
        exporters: [loki]
