CREATE USER todo_user WITH PASSWORD '<PASSWORD>';
GRANT CONNECT ON DATABASE todo_app TO todo_user;
GRANT USAGE ON SCHEMA public TO todo_user;
GRANT USAGE, SELECT ON SEQUENCE id_seq TO todo_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO todo_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO todo_user;
