{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notifier-service
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: notifier-service
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
  {{- end }}
