loki:
  persistence:
    enabled: true
    size: 5Gi
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 15d

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
