tempo:
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
