# Server Configuration
server:
  port: ${server.port}
  
# Database Configuration
spring:
  application:
    name: todo-application
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${database_password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  cloud:
    gcp:
      project-id: ${gcp.project-id}
      config:
        project-id: ${gcp.project-id}
      logging:
        enabled: true

# Spring Security
jwt:
  expirationMs: 3600000

# Logging
logging:
  level:
    root: ${logging.level.root}
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ${management.endpoints.web.exposure.include}
