# Server Configuration
server:
  port: 8080

# Database Configuration
spring:
  application:
    name: todo-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo_service
#    url: jdbc:h2:mem:todos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
    username: todo_user
    password: admin
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

# Logging
logging:
  level:
    root: INFO
#  pattern:
#    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","thread":"%t","logger":"%c","message":"%m"}\n'

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

otel:
  endpoint: "http://otel-collector:4317"

aws:
  sqs:
    queue-url: http://localhost:4566/000000000000/todo-events
    region: us-east-1
    endpoint: http://localhost:4566