replicaCount: 2

image:
  repository: your-dockerhub/notifier-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  AWS_REGION: "us-east-1"
  SQS_QUEUE_URL: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  LOG_LEVEL: "info"

serviceMonitor:
  enabled: true
  interval: 30s

nodeSelector: {}
tolerations: []
affinity: {}
