apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: canaryreleases.ops.example.com
spec:
  group: ops.example.com
  names:
    kind: CanaryRelease
    plural: canaryreleases
    singular: canaryrelease
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetRef:
                  type: object
                image:
                  type: string
                canaryPercent:
                  type: integer
                durationMinutes:
                  type: integer
                successCriteria:
                  type: object
                properties:
                errorRateThreshold:
                  type: number
                latencyP95Ms:
                  type: integer
  subresources:
    status: {}