global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'todo-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['todo-service:8080']

  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8888']
