name: CI Build & Push
pull_request:
branches: [ main ]


env:
AWS_REGION: us-east-1


jobs:
build-and-push:
runs-on: ubuntu-latest
permissions:
contents: write
id-token: write
steps:
  - uses: actions/checkout@v4


  - name: Set up JDK 17
uses: actions/setup-java@v4
with:
distribution: temurin
java-version: '17'


  - name: Set up Go
uses: actions/setup-go@v4
with:
go-version: '1.20'


  - name: Login to AWS (OIDC)
uses: aws-actions/configure-aws-credentials@v2
with:
role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
aws-region: ${{ env.AWS_REGION }}


  - name: Build todo-service (Gradle)
working-directory: ./apps/todo-service
run: ./gradlew build -x test


  - name: Build notifier-service (Go)
working-directory: ./apps/notifier-service
run: |
  CGO_ENABLED=0 go build -o notifier ./...


- name: Login to ECR
run: |
  aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com


- name: Build and Push todo image
working-directory: ./apps/todo-service
run: |
  IMAGE=${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/todo-service:${{ github.sha }}
  docker build -t $IMAGE .
  docker push $IMAGE


- name: Build and Push notifier image
working-directory: ./apps/notifier-service
run: |
  IMAGE=${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/notifier-service:${{ github.sha }}
  docker build -t $IMAGE .
  docker push $IMAGE


- name: Create/Update gitops repo values (commit image tags)
# This step assumes you have a PAT stored in secrets.GITOPS_REPO_TOKEN
run: |
# simple approach: use git to clone deploy/gitops, update values.yaml and push
  git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/${{ github.repository_owner }}/deploy-gitops.git /tmp/gitops
  cd /tmp/gitops/apps/todo
  yq eval ".image.tag = \"${{ github.sha }}\"" -i values.yaml
git add . && git commit -m "ci: update todo image ${{ github.sha }}" || true
  git push